spring.application.name=convert-exchange-rate

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/productdb
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.sql.init.mode=always

app.exchange-api.url=http://localhost:3000